### ISSUE TITLE
[yarn-4.x] `latest` isn't supported by any available resolver

### ISSUE THREAD

**Issue by rtritto** [mskelton/yarn-plugin-outdated#50]
After updating yarn to _v4.0.0-rc.2_, the plugin stops to work.

## Steps to reproduce

```sh
yarn init -y
yarn set version canary
yarn add @emotion/cache
yarn plugin import https://mskelton.dev/yarn-outdated/v2
yarn outdated
```

## Actual
```console
➤ YN0000: ┌ Checking for outdated dependencies
➤ YN0001: │ Error: @emotion/cache@latest isn't supported by any available resolver
    at Ym.getResolverByDescriptor (C:\0-outdated\.yarn\releases\yarn-4.0.0-rc.2.cjs:135:1721)
    at Ym.bindDescriptor (C:\0-outdated\.yarn\releases\yarn-4.0.0-rc.2.cjs:135:1106)
    at Object.hU (C:\0-outdated\.yarn\releases\yarn-4.0.0-rc.2.cjs:378:10959)
    at ze.fetch (C:\0-outdated\.yarn\plugins\@yarnpkg\plugin-outdated.cjs:7:28220)
    at C:\0-outdated\.yarn\plugins\@yarnpkg\plugin-outdated.cjs:8:2348
    at Array.map (<anonymous>)
    at Ee.getOutdatedDependencies (C:\0-outdated\.yarn\plugins\@yarnpkg\plugin-outdated.cjs:8:2217)
    at C:\0-outdated\.yarn\plugins\@yarnpkg\plugin-outdated.cjs:8:376
    at Ft.startSectionPromise (C:\0-outdated\.yarn\releases\yarn-4.0.0-rc.2.cjs:161:2954)
    at Ft.startTimerPromise (C:\0-outdated\.yarn\releases\yarn-4.0.0-rc.2.cjs:161:3834)
➤ YN0000: └ Completed
```

## Expect
No error

**Comment by mskelton** [comment]
Cannot reproduce with rc 3.
